name: Check
on: push
jobs:
    os:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout 
              uses: actions/checkout@v6
            - name: Install deps
              run: |
                docker --version 
                docker info


            - name: TestDocker
              run: |
                cd docker-nginx-reverse-proxy/docker_nginx/
                Docker build .
